---
- hosts: "{{ HOSTS }}"
  become: yes
  gather_facts: no

  tasks:
    - name: install important packages
      vars:
        ansible_python_interpreter: /usr/bin/python
      package:
        name:
          - htop
          - tmux
          - vim
          - curl
          - python3-setuptools
          - python3-pip
        state: present

    - name: install docker module for python
      vars:
        ansible_python_interpreter: /usr/bin/python3
      pip:
        name:
          - docker
          - docker-compose